name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/ResumeRanker
          git pull origin main
          docker stop flask-container || true
          docker rm flask-container || true
          docker build -t flask-app .
          docker run -d -p 16832:5000 --name flask-container flask-app
        EOF
